# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: check-docstring-first
    -   id: check-case-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-symlinks
    -   id: check-vcs-permalinks
    -   id: debug-statements
    -   id: forbid-submodules
    -   id: no-commit-to-branch
        args:
        - --branch=main
        - --pattern="release/*"

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.2
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      args:
            - --line-length=79
            - --exclude="""\.git |
              \.__pycache__|
              \.hg|
              \.mypy_cache|
              \.tox|
              \.venv|
              _build|
              buck-out|
              build|
              dist|
              docs"""

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v3.4.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: []
