# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    # Black formattting
-   repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
    -   id: black
        args:
            - --line-length=79

            # these folders wont be formatted by black
            - --exclude="""\.git |
              \.__pycache__|
              \.hg|
              \.mypy_cache|
              \.tox|
              \.venv|
              _build|
              buck-out|
              build|
              dist|
              docs"""

        # black depends on click
        additional_dependencies: ["click>=8"]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
