name: Feature Request
description: Request a feature
title: "[Feat]: "
labels: ["enhancement"]
projects: []
assignees:
  - teald
body:
  - type: markdown
    attributes:
      value: |
        Thank you for requesting a new feature! Your input is critical to helping us make `astrodata` even better!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info? If you get notification for GitHub Issues, you can ignore this part.
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature in words
      description: "Tell us about your feature request. Example questions to consider: What does it do? How might it be implemented?"
      placeholder: I'd like astrodata to...
    validations:
      required: true
  - type: textarea
    id: code-description
    attributes:
      label: code-description
      description: If possible, please provide an example code snippet with the feature being used. It doesn't have to run---show us code the way you'd like it to work!
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/GeminiDRSoftware/astrodata/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
