name: Other issue
description: File an issue unrelated to the other templates
title: "[MISC]: "
labels: ["misc"]
projects: []
assignees:
  - teald
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filling out a bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info? If you get notification for GitHub Issues, you can ignore this part.
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see.
      value: "Something happened!"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/GeminiDRSoftware/astrodata/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
