# Purges the camo cache for update purposes, once a day.
name: Purge caches

on:
  workflow_dispatch:


jobs:
  purge-camo:
    runs-on: ubuntu-latest
    steps:
      - name: Purge camo cache
        uses: kevincobain2000/action-camo-purge@v1
