name: PyPI package

on:
  push:
    tags:
      # Matches any tags; tags are only used for versioning in this project.
      - '*'
  workflow_dispatch:

jobs:
  source_test:
    # This runs the test files on the repository before publishing it.
    name: Source tests
    uses: ./.github/workflows/source_tests.yml

  build_test:
    name: Build tests
    uses: ./.github/workflows/build_tests.yml

  deploy:
    needs: [source_test, build_test]
    runs-on: ubuntu-latest

    permissions:
      # This permission is required for trusted publishing.
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Update version (kept at 0.0.0) in pyproject.toml and build
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          poetry version ${{ github.ref_name }}
          poetry version
          poetry build

      - name: Mint token
        if: ${{ github.event_name != 'workflow_dispatch' }}
        id: mint
        uses: tschm/token-mint-action@v1.0.3

      - name: Publish the package with poetry
        # Allow workflow dispatch to trigger this job, but don't allow it
        # to publish the package to PyPI.
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
           echo "PUBLISHING!!!! ✨🚀"
           poetry publish -u __token__ -p '${{ steps.mint.outputs.api-token }}'
