name: PyPI package

on:
  push:
    tags:
      # Matches any tags; tags are only used for versioning in this project.
      - '*'
      - '!*dev*'
  workflow_dispatch:

jobs:
  source_test:
    # This runs the test files on the repository before publishing it.
    name: Source tests
    uses: ./.github/workflows/source_tests.yml

  build_test:
    name: Build tests
    uses: ./.github/workflows/build_tests.yml

  build:
    name: Build package
    needs: [source_test, build_test]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v2
    with:
      python-version: '3.12'
      save_artifacts: true
      upload_to_pypi: false   # never let this workflow attempt the upload itself

  upload:
    name: Upload to PyPI
    if: ${{ github.event_name != 'workflow_dispatch' }}
    needs: [build]
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/project/astrodata/

    permissions:
      id-token: write   # required for trusted publishing

    steps:
      - name: Download built dists
        uses: actions/download-artifact@v7
        with:
          merge-multiple: true
          pattern: dist-*
          path: dist

      - name: Publish the package
        uses: pypa/gh-action-pypi-publish@release/v1